obj-$(CONFIG_DISPLAY_PORT_DRIVER) += dp_driver.o \
                                     main.o \
                                     txlink.o \
                                     edid.o \
                                     dptx.o \
                                     dptxaux.o \
                                     dprx.o \
                                     dpdbg.o






